# -*- coding: utf-8 -*-
"""worksheet1exp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJKh-1FLRqPEcp8qmBG5y85731KXDNNw
"""

import numpy as np
import random
from timeit import timeit

size = 1000000
Z1_list = random.sample(range(size + 1), size)
Z2_list = random.sample(range(size + 1), size)
Z1_np = np.array(Z1_list)
Z2_np = np.array(Z2_list)

#1. Element-wise Addition:

# Define addition functions
def add_python(Z1, Z2):
    return [z1 + z2 for z1, z2 in zip(Z1, Z2)]

def add_numpy(Z1, Z2):
    return np.add(Z1, Z2)

# Time the execution of each function
python_time = timeit("add_python(Z1_list, Z2_list)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(Z1_np, Z2_np)", globals=globals(), number=100)

# Print results
print(f"Pure Python addition: {python_time:.6f} seconds per loop")
print(f"NumPy addition: {numpy_time:.6f} seconds per loop")

#Element-wise Multiplication

# Define multiplication functions
def multiply_python(Z1, Z2):
    return [z1 * z2 for z1, z2 in zip(Z1, Z2)]

def multiply_numpy(Z1, Z2):
    return np.multiply(Z1, Z2)

# Time the execution of each function
python_time = timeit("multiply_python(Z1_list, Z2_list)", globals=globals(), number=100)
numpy_time = timeit("multiply_numpy(Z1_np, Z2_np)", globals=globals(), number=100)

# Print results
print(f"Pure Python multiplicaton: {python_time:.6f} seconds per loop")
print(f"NumPy multiplication: {numpy_time:.6f} seconds per loop")

#Dot Product
# Define multiplication functions
def dot_python(Z1, Z2):
    result=[z1 * z2 for z1, z2 in zip(Z1, Z2)]
    return sum(result)

def dot_numpy(Z1, Z2):
    return np.dot(Z1, Z2)

# Time the execution of each function
python_time = timeit("dot_python(Z1_list, Z2_list)", globals=globals(), number=100)
numpy_time = timeit("dot_numpy(Z1_np, Z2_np)", globals=globals(), number=100)

# Print results
print(f"Pure Python dot product: {python_time:.6f} seconds per loop")
print(f"NumPy dot product: {numpy_time:.6f} seconds per loop")

#Matrix Multiplication

rows=1000
columns=1000

python_matrix1=[[random.randint(0,1000) for _ in range(columns)] for _ in range(rows)]
numpy_matrix1=np.array(python_matrix1)

python_matrix2=[[random.randint(0,1000) for _ in range(columns)] for _ in range(rows)]
numpy_matrix2=np.array(python_matrix2)

def matrix_python_multiplication(Z1, Z2):
    rows_a=len(Z1)
    cols_a=len(Z1[0])
    rows_b=len(Z2)
    cols_b=len(Z2[0])

    result = [[0 for _ in range(cols_b)] for _ in range(rows_a)]
    for i in range(rows_a):
      for j in range(cols_b):
        for k in range(cols_a):
          result[i][j]+= Z1[i][k]*Z2[k][j]
    return result
def matrix_numpy_multiplication(Z1, Z2):
    return np.matmul(Z1, Z2)

# Time the execution of each function
python_time = timeit("matrix_python_multiplication(python_matrix1, python_matrix2)", globals=globals(), number=100)
numpy_time = timeit("matrix_numpy_multiplication(numpy_matrix1, numpy_matrix2)", globals=globals(), number=100)

# Print results
print(f"Pure Python multiplicaton: {python_time:.6f} seconds per loop")
print(f"NumPy multiplication: {numpy_time:.6f} seconds per loop")