# -*- coding: utf-8 -*-
"""worksheet1(practice).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7VFEeJ5EAfvc6MEi8gXoNaONlufF_X5
"""

import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

import numpy as np
# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
    print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

array = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
reshaped_array = array.reshape(3, 2) # Reshape to (3, 2), keeping 6 elements
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

import numpy as np
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arrange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

import numpy as np
# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Concatenate along axis 0 (vertical) Shape: (4, 2)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Concatenate along axis 1 (horizontal) Shape: (2, 4)
print(concat_axis0, concat_axis1, sep='\n')

import numpy as np
# Arrays
arr1d = np.array([0, 1, 2, 3, 4, 5])
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]])
# Slicing examples
print("Basic:", arr1d[1:4], arr2d[1:3, 0:2], arr3d[1:2, 0:2, 1:2])
# Output Basic: arr1d:[1 2 3] arr2d:[[3 4] [6 7]] arr3d:[[[5] [7]]]
print("Step:", arr1d[1:5:2], arr2d[::2, 1::2], arr3d[::2, ::2, 1::2])
# Output: Step: [1 3] [[1] [7]] [[[1] [9]]]

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Add:", np.add(arr1, arr2)) # Output Add: [5 7 9]
print("Subtract:", np.subtract(arr1, arr2))
# Output Subtract: [-3 -3 -3]
print("Divide:", np.divide(arr1, arr2))
# Output Divide: [0.25 0.4 0.5]
print("Multiply:", np.multiply(arr1, arr2))
# Output Multiply: [ 4 10 18]
print("Power:", np.power(arr1, arr2))
# Output Power: [ 1 32 729]
print("Exp:", np.exp(arr1))
# Output Exp: [ 2.71828183 7.3890561 20.08553692]

import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using np.dot
result_dot = np.dot(A, B)
print("Result with np.dot:\n", result_dot) # Output shape: (2, 2)

import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using @ operator
result_at = A @ B
print("Result with @ operator:\n", result_at) # Output shape: (2, 2)
# Matrix multiplication using np.matmul
result_matmul = np.matmul(A, B)
print("Result with np.matmul:\n", result_matmul) # Output shape: (2, 2)

import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse:\n", np.linalg.inv(A))
# Output: Inverse: [[-2. 1. ], [ 1.5 -0.5]]
print("Determinant:", np.linalg.det(A))
# Output: Determinant: -2.0
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
# Output: Frobenius Norm: 5.4772
print("2-Norm (Euclidean):", np.linalg.norm(A))
# Output: 2-Norm(Euclidean): 5.4772
print("Solution x:", np.linalg.solve(A, B))
#Output: Solution x: [-4. 4.5]

