# -*- coding: utf-8 -*-
"""worksheet0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nep2BT4EIK6swTwFiHLBa9feFi_zw5tD
"""

time_data = [ (3.5, 2.0, 7.0), (5.0, 1.5, 6.5), (2.5, 3.0, 8.0),
    (4.0, 2.0, 6.0), (1.5, 4.5, 9.0), (3.0, 2.5, 7.5),
    (5.5, 1.0, 6.0), (2.0, 3.5, 8.5), (4.5, 2.0, 7.0),
    (3.0, 3.0, 7.5), (6.0, 1.5, 6.0), (2.5, 4.0, 8.0),
    (4.0, 2.5, 7.0), (5.0, 2.0, 6.5), (3.5, 2.5, 7.0) ]

low, moderate, high= list(),list(),list()

for i in time_data:
    if i[0]<3 :
        low.append(i[0])
    elif i[0]>=3 and i[0]<=5:
        moderate.append(i[0])
    else:
        high.append(i[0])

print("Low: ",low)
print("moderate: ",moderate)
print("high: ",high)

print("Number of low study time: ",len(low))
print("Number of moderate study time: ",len(moderate))
print("Number of low study time: ",len(high))

study_minutes=list()

for i in time_data:
    minutes=i[0]*60
    study_minutes.append(minutes)

print(study_minutes)

study_hours,entertainment_hours,sleep_hours=list(),list(),list()

for i in time_data:
    study_hours.append(i[0])
    entertainment_hours.append(i[1])
    sleep_hours.append(i[2])

print("Average study hour: ",sum(study_hours)/15)
print("Average entertainment hours: ",sum(entertainment_hours)/15)
print("Average sleep hours: ",sum(sleep_hours)/15)

import matplotlib.pyplot as plt

plt.scatter(study_hours,sleep_hours,c="red")
plt.title("Visualization- Study vs Sleep Pattern")
plt.xlabel("Study hours")
plt.ylabel("sleep hours")
plt.show()

def sum_nested_list(nested_list):
    sum=0
    for i in nested_list:
        if isinstance(i,list):
            sum=sum+sum_nested_list(i)
        else:
            sum+=i
    return sum

nested_list = [1, [2, [3, 4], 5], 6, [7, 8]]
print(sum_nested_list(nested_list))
print(sum_nested_list([1, [2, 3], [4, [5]]]))

def generate_permutations(s):
    all_permutation=list()
    if len(s)==1:
        return [s]
    else:
        for i in range(len(s)):
            char = s[i]
            remain=s[:i]+s[i+1:]
            for j in generate_permutations(remain):
                new_per=char+j
                if new_per not in all_permutation:
                    all_permutation.append(new_per)
        return all_permutation

print(generate_permutations("abc"))
print(generate_permutations("aab"))

def min_coins(coins,amount):
    dp=[float('inf')]*(amount+1)
    dp[0]=0
    for coin in coins:
        for i in range(coin,amount+1):
            dp[i]=min(dp[i],dp[i-coin]+1)
    return dp[amount] if dp[amount]!= float('inf') else -1

print(min_coins([1,2,5],11))

def longest_common_subsequence(s1, s2):
    m=len(s1)
    n=len(s2)
    dp=[[0]*(m+1) for _ in range(n+1)]
    for i in range(1,n+1):
        for j in range(1,m+1):
            if s2[i-1]==s1[j-1]:
                dp[i][j]=dp[i-1][j-1]+1
            else:
                dp[i][j]=max(dp[i-1][j],dp[i][j-1])
    return dp[n][m]

s1='abcde'
s2='ace'

print(longest_common_subsequence(s1, s2))

def knapsack(weights, values, capacity):
    dp=[0]*(capacity+1)
    for i in range(0,len(weights)):
        for j in range(weights[i],capacity+1):
            dp[j]=max(values[i]+dp[j-weights[i]],dp[j])
    return dp[capacity]

weights=[1, 3, 4, 5]
values=[1, 4, 5, 7]
capacity=7

print(knapsack(weights, values, capacity))