# -*- coding: utf-8 -*-
"""worksheet2todo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AjIZp2kOtOev9bwUAVat4wPNzRK5LHcy
"""

import pandas as pd

#Problem 1 - Data Read, Write and Inspect:
#1. Load the provided dataset and import in pandas DataFrame.
dataset = pd.read_csv("bank.csv")

#2. Check info of the DataFrame and identify following:
#(a) columns with dtypes=object
#(b) unique values of those columns.
#(c) check for the total number of null values in each column.
dataset.info()
obj_dataset_column = dataset.select_dtypes("object").columns
print(obj_dataset_column)

#3. Drop all the columns with dtypes object and store in new DataFrame, also write the DataFrame in
#”.csv” with name ”banknumericdata.csv”
new_dataset=dataset.drop(columns=obj_dataset_column)
new_dataset.info()
new_dataset.to_csv("banknumericdata.csv")

#Read ”banknumericdata.csv” and Find the summary statistics.
numeric_dataset=pd.read_csv('banknumericdata.csv')
numeric_dataset.describe()



######################################################################################################################

#Dataset for the Task: "medical_student.csv"
#1. Load the provided dataset and import in pandas DataFrame.
medical_dataset=pd.read_csv("medical_students_dataset.csv")


#2. Check info of the DataFrame and identify column with missing (null) values.
medical_dataset.info()

#3.For the column with missing values fill the values using various techniques we discussed above. Try
#to explain why did you select the particular methods for particular column.
medical_dataset['Student ID']=medical_dataset['Student ID'].fillna((medical_dataset['Student ID'].ffill())+1)
medical_dataset['Age']=medical_dataset['Age'].fillna(medical_dataset['Age'].mean())
medical_dataset['Gender']=medical_dataset['Gender'].ffill()
medical_dataset['Height']=medical_dataset['Height'].fillna(medical_dataset['Height'].median())
medical_dataset['BMI']=medical_dataset['BMI'].fillna(medical_dataset['BMI'].median())
medical_dataset['Temperature']=medical_dataset['Temperature'].fillna(medical_dataset['Temperature'].mean())
medical_dataset['Blood Pressure']=medical_dataset['Blood Pressure'].fillna(medical_dataset['Blood Pressure'].median())
medical_dataset['Cholesterol']=medical_dataset['Cholesterol'].fillna(medical_dataset['Cholesterol'].median())
medical_dataset['Blood Type']=medical_dataset['Blood Type'].ffill()
medical_dataset['Weight']=medical_dataset['Weight'].fillna(medical_dataset['Weight'].median())
medical_dataset['Diabetes']=medical_dataset['Diabetes'].ffill()
medical_dataset['Heart Rate']=medical_dataset['Heart Rate'].fillna(medical_dataset['Heart Rate'].mean())
medical_dataset['Smoking']=medical_dataset['Smoking'].fillna(0)

#4. Check for any duplicate values present in Dataset and do necessary to manage the duplicate items.
print(medical_dataset.duplicated().sum())
medical_dataset.drop_duplicates()