# -*- coding: utf-8 -*-
"""worksheet1todo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vDQJlG_-bL4nrIQLizjjVuK6baBVsczd
"""

import numpy as np
#problem1

arr_empty=np.empty((2,2))
arr_ones=np.ones((4,2))
arr_full=np.full((3,3),2)
arr_zeros=np.zeros_like(arr_full)
arr_ones_like=np.ones_like(arr_full)

new_list=[1,2,3,4]

np_new_list=np.array(new_list)

print(arr_empty)
print(arr_ones)
print(arr_full)
print(arr_zeros)
print(arr_ones_like)
print(np_new_list)

#problem2
#Create an array with values ranging from 10 to 49.
arr = np.arange(10,49)
print(arr)

#Create a 3X3 matrix with values ranging from 0 to 8.
arr_reshaped=np.reshape(np.arange(0,9),(3,3))
print(arr_reshaped)

#Create a 3X3 identity matrix
arr_identity=np.eye(3,3)
print(arr_identity)

#Create a random array of size 30 and find the mean of the array.
arr_random=np.random.random(size=30)
print("Mean: ",arr_random.mean())

#Create a 10X10 array with random values and find the minimum and maximum values.
arr_random10=np.random.random_integers(100,size=(10,10))
print("Max: ",np.max(arr_random10))
print("Min: " ,np.min(arr_random10))

#Create a zero array of size 10 and replace 5th element with 1.
arr_zeros10=np.zeros(10)
print(arr_zeros10)
arr_zeros10[4]=1
print(arr_zeros10)

#Reverse an array arr = [1,2,0,0,4,0].
arr=[1,2,0,0,4,0]
arr_reversed=arr[::-1]
print(arr_reversed)
print(arr)

#Create a 2d array with 1 on border and 0 inside.
arr_2d=np.zeros((3,3))
arr_2d[0:3:2,0:3]=1
arr_2d[1:2,0:3:2]=1
print(arr_2d)

#Create a 8X8 matrix and fill it with a checkerboard pattern.
arr_checker=np.zeros((8,8))
arr_checker[0:9:2,0:9:2]=1
arr_checker[1:9:2,1:9:2]=1
print(arr_checker)

#problem3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#Add the two array.
arr_add1=np.add(x,y)
arr_add2=np.add(v,w)
print(arr_add1)
print(arr_add2)

#Subtract the two array.
arr_sub1=np.subtract(x,y)
arr_sub2=np.subtract(v,w)
print(arr_sub1)
print(arr_sub2)

#Multiply the array with any integers of your choice.
arr_prod=5*x
print(arr_prod)

#Find the square of each element of the array.
arr_square=np.square(x)
print(arr_square)

#Find the dot product between: v(and)w ; x(and)v ; x(and)y.
arr_dot1=np.dot(v,w)
arr_dot2=np.dot(x,v)
arr_dot3=np.dot(x,y)
print(arr_dot1)
print(arr_dot2)
print(arr_dot3)

#Concatenate x(and)y along row and Concatenate v(and)w along column.
arr_hor=np.hstack((x,y))
arr_ver=np.vstack((x,y))
print(arr_hor)
print(arr_ver)

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
I = np.eye(2,2)

#1. Prove A.A−1 = I.
A_inv=np.linalg.inv(A)
result= A @ A_inv
print("\nIs A * A_inv equal to identity matrix?")
print(np.allclose(result, I))

#2. Prove AB ̸= BA.
prod1=A @ B
prod2= B @ A
print("Is AB=BA")
print(np.allclose(prod1,prod2))

#3. Prove (AB)T = BTAT
A_trans=np.linalg.matrix_transpose(A)
B_trans=np.linalg.matrix_transpose(B)
AB=A @ B
AB_trans=np.linalg.matrix_transpose(AB)
result= B_trans @ A_trans
print("Is transpose AB equal to transpose A * transpose B")
print(np.allclose(result, AB_trans))


'''Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
'''

eq_A=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
eq_B=np.array([-1,-3,9])
inv_eq_A=np.linalg.inv(eq_A)
X=inv_eq_A @ eq_B
print("x: ",X[0]," y: ",X[1]," z: ",X[2])